apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
        - name: vproapp
          image: j4ro123/vprofileapp:V1
          ports:
            - name: vproapp-port
              containerPort: 8080
      # initContainers:
      #   - name: init-mydb
      #     image: busybox
      #     command: ['sh', '-c', 'until nslookup vprodb.prod.svc.cluster.local; do echo waiting for mydb; sleep 2; done;']
      #   - name: init-memcache
      #     image: busybox
      #     command: ['sh', '-c', 'until nslookup vprocache01.prod.svc.cluster.local; do echo waiting for mydb; sleep 2; done;']